name: Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Validate current commit (last commit) with commitlint
        run: bunx commitlint --last --verbose

      - name: Lint
        run: bun run lint

      - name: Format
        run: bun run format
